### ISSUE TITLE
Add more Info about uploaded vocabs and examples

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-reconcile-publish#18]
Feedback by @nichtich from [metadaten.community post](https://metadaten.community/t/skohub-reconcile-reconciliation-skos/190/2)

> Danke! Es wäre einfacher wenn auf der Startseite ein oder mehrere Beispiele von vorhandenen Datensätzen aufgeführt werden.Nach dem Hochladen wäre außerdem ein ausführlicherer Hinweis nett, wie viele Einträge das Vokabular hat und wie lange es öffentlich verfügbar sein wird.

**Comment by acka47** [comment]
This should be easy to address:

1. Add some Service Manifest links to example vocabs.
2. Add a note after upload that says something like:
> This service is currently in Alpha and may go offline or uploaded data might get lost.

Re. 1.) we should add example vocabs that are 
1. known by a wider community
2. not already listed at https://reconciliation-api.github.io/testbench/#/

**Comment by sroertgen** [comment]
Do you have any specific suitable vocabs in mind? We could use something like the [Hochschulfächersystematik](https://w3id.org/kim/hochschulfaechersystematik/scheme) for example.

**Comment by acka47** [comment]
Yes, Hochschulfächersystematik is fine. Here are some more ideas. It might be some work for some cases, though, as they are quite big and maybe some do not conform to the SkoHub Shape yet. But we could run the shape test and see whether it is doable.

Thesauri:
- STW: https://zbw.eu/stw/version/latest/download/about.en.html
- AgroVoc: https://data.apps.fao.org/catalog/dcat/agrovoc-2023-12
- Rameau: data dump linked via https://api.bnf.fr/fr/dumps-de-databnffr
- UNESCO Thesaurus: https://vocabularies.unesco.org/browser/en/about

These are all thesauri, though. I will have to think about another classification.
