### ISSUE TITLE
Offer alternatives for providing an account

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-reconcile-publish#19]
Ideas:

- use GitHub or other authentication
- or ORCID

**Comment by sroertgen** [comment]
@acka47 What do you think about using ORCID for providing the account information?

The authentication widget didn't look to complicated to integrate. I could test it. ORCID also seems a little less big corp than GitHub

**Comment by acka47** [comment]
ORCID sounds good to me. I also like the GBV login server that is used at https://bartoc.org, see https://github.com/gbv/login-server. Maybe this is something we could reuse...

**Comment by sroertgen** [comment]
Note
orcid sandbox environment seems to be not working right now. Waiting for answer from support.
